apiVersion: v1
kind: Pod
metadata:
  name: drifter-sync
  labels:
    tier: api
spec:
  volumes:
    - name: drifters
      persistentVolumeClaim:
        claimName: drifters-raw
  containers:
  - name: schema
    imagePullPolicy: Always
    image: argovis/drifter-sync:dev
    command: ['sleep', '1000000']
    #command: ['python', 'download-drifters.py']
    #command: ['bash', 'loaddata.sh']
    volumeMounts:
      - mountPath: "/tmp/drifters"
        name: drifters
    resources:
      requests:
        memory: "0Gi"
        cpu: "0m"
      limits:
        memory: 1Gi
        cpu: 1000m
  restartPolicy: Never
